<div class="out_table" style="display: <?php echo $this->form_display; ?> ">
    <div class="out_table_label" >Source mailbox parameters:</div>
    <?php echo $this->form ?>
</div>

<div class="out_table" >
    <div class="out_table_label" >Transfer parameters</div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Direction</th>
                <th>Host</th>
                <th>User</th>
                <th>Password</th>
            </tr>
        </thead>
        <tbody>
            <?php $i = 1; ?>
            <?php foreach ($this->t_servers as $server): ?>

                <tr>
                    <td><?php echo $this->escape($server[0]); ?></td>
                    <td><?php echo $this->escape($server[1]); ?></td>
                    <td><?php echo $this->escape($server[2]); ?></td>
                    <td><?php echo $this->escape($server[3]); ?></td>
                    <td>
                        <a href="<?php echo $this->url(array('controller' => 'logged', 'action' => 'edit', 'id' => $server[4])); ?>" class="btn btn-default" >Edit</a>
                        <a href="<?php echo $this->url(array('controller' => 'logged', 'action' => 'delete', 'id' => $server[4])); ?>" class="btn btn-warning" >Delete</a>
                    </td>
                </tr>
                <?php $i++; ?>
            <?php endforeach; ?>
            <tr>
                <td colspan="5" align="center"><a href="/logged/add" class="btn btn-primary" >Add source server</a>
                    &nbsp;&nbsp;<a href="logged/transfer" class="btn btn-primary" >Begin transfer</a>
            </tr>          
        </tbody>
    </table>     
</div>
