<div class="out_table" align="center"> 
    <div class="row-fluid" align="center">
        <p>Enter the number you obtain when you successfully finish enter main page data, given to you as the Process number.</p> 
    </div>
</div>
<div class="out_table" align="center"> 
    <div class="row" align="center">
        
        <div class="col-md-2 col-md-offset-5">
            <p><?php echo $this->form ?></p>
        </div>
    </div>
</div>
<div class="out_table" align="center"> 
    <div class="row-fluid" align="center">
        <p><?php echo $this->mess ?></p> 
    </div>
</div>
