<div class="out_table bg-success" >
    <p>This is Your Process Number. Please write it down or remember to have ability of knowing progress of Your transfer. Go to check page to know it.</p>
</div>
<div class="row">
    <div class="col-md-12 text-center">
        <h5 class="number"><?php echo $this->process_number ?></h2>
        <p>tu może być tekst zachęcajacy do logowania, </p>
        <p>albo reklama webiona</p>
        <p>reklama homepaya</p>
        <p>jakiś obrazek</p>
    </div>
</div>