<div class="out_table" align="center"> 
    <p>This is Your Process Number. Please write it down or remember to have ability of knowing progress of Your transfer. 
        Go to check page to know it.</p>

</div>
<div class="out_table" align="center"> 
    <div class="row-fluid" align="center">
        <h2><?php echo $this->process_number ?></h2>    
    </div>
</div>
<div class="out_table" align="center"> 
    <div class="row-fluid" align="center">
        
        <p>tu może być tekst zachęcajacy do logowania, </p>
        <p>albo reklama webiona</p>
        <p>reklama homepaya</p>
        <p>jakiś obrazek</p>
    </div>
</div>
