<div class="out_table bg-success" >
	<p>Enter the number you obtain when you successfully finish enter main page data, given to you as the Process number.</p> 
</div>
<div class="out_table" align="center"> 
    <div class="row-fluid" align="center">
         <p><?php echo $this->form ?></p>
    </div>
</div>
<div class="out_table" align="center"> 
    <div class="row-fluid" align="center">
         <p><?php echo $this->mess ?></p> 
    </div>
</div>
<!--<p>Enter the number you obtain when you successfully finish enter main page data, given to you as the Process number.</p>

<p><?php// echo $this->form ?></p>-->