<article class="search">
<!-- I get the action and method from the form but they were added in the controller -->
    <form action="<?php echo $this->element->getAction() ?>"
          method="<?php echo $this->element->getMethod() ?>">
        <table>
            <tr>
            <!-- renderLabel() renders the Label decorator for the element
                <th><?php echo $this->element->query->renderLabel() ?></th>
            </tr>
            <tr>
            <!-- renderViewHelper() renders the actual input element, all decorators can be accessed this way -->
                <td><?php echo $this->element->query->renderViewHelper() ?></td>
            </tr>
            <tr>
            <!-- this line renders the submit element as a whole -->
                <td><?php echo $this->element->search ?></td>
            </tr>
        </table> 
    </form>
</article>