<div class="out_table" align="center"> 
    <div class="out_table bg-success" >
        <p>This site allows you to move all your email messages from old mailbox to the new one. It also have a functionality of moving few the old ones at once. Try it !</p>
    </div>
    <div class="row-fluid" align="center">
        <a href="<?php echo $this->url(array('controller' => 'transfer', 'action' => 'param')) ?>" class="btn btn-primary"><i class="fa fa-power-off last"></i><span class="hidden-xs hidden-sm">Continue without login</span></a>
    </div>
</div>
<div class="out_table">

    <div class="row" >
        <div class="col-md-5"></div> 
        <div class="col-md-2 col-md-offset5">
            <div class="form-group">
                <?php echo $this->form ?> 
                <a href="auth/register" style="font-size: 12px">New? Register</a>
            </div>       
        </div>
    </div>
</div> 

