<div class="out_table bg-success" >
	<p>This site allows you to move all your email messages from old mailbox to the new one. It also have a functionality of moving few the old ones at once. Try it !</p>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <?php echo $this->form ?> 
        <a href="<?php echo $this->url(array('controller' => 'transfer', 'action' => 'param')) ?>" class="btn">Continue without login</span></a>
        <a href="auth/register" class="btn red">New? Register</a>
    </div>
</div>