<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Imap transfer</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
        <?php echo $this->headLink()->appendStylesheet('/css/style.css') ?>
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,700,900&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <header>
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="logo">
                            <img src="/images/logo_webion.png" />
                        </div>
                        <div class="menu" style="display: <?php echo $this->menu_display ?>">
                            <ul class="unstyled">
                                <li><a href="/index/">Home</a></li>
                                <li><a href="/transfer/param">Mailbox transfer</a></li>
                                <li><a href="/transfer/check">Check</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!--nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container" style="border: 0px">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/index/">Home</a>
                    
                </div>
                <div id="navbar" class="collapse navbar-collapse" style="display: <?php echo $this->menu_display ?>" >
                    <ul class="nav navbar-nav">
                        <li><a href="/transfer/param">Mailbox transfer</a></li>
                        <li><a href="/transfer/check">Check</a></li>
                        <!--<li><a href="/transfer/session">Contact</a></li>>
                    </ul>
                </div>
            </div>
        </nav-->
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h3>Mailbox transfer</h3>     
                    <?php echo $this->layout()->content; ?>            
                </div>
            </div>
        </div>
        <?php echo $this->headScript()->prependFile($this->baseUrl('/js/bootstrap.min.js')) ?>
    </body>
</html>