<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Imap transfer</title>
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
        <?php echo $this->headLink()->appendStylesheet('/css/style.css') ?>
        
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container" style="border: 0px">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/index/">Home</a>
                    
                </div>
                <div id="navbar" class="collapse navbar-collapse" style="display: <?php echo $this->menu_display ?>" >
                    <ul class="nav navbar-nav">
                        <li><a href="/transfer/param">Mailbox transfer</a></li>
                        <li><a href="/transfer/check">Check</a></li>
                        <!--<li><a href="/transfer/session">Contact</a></li>-->
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <p>&nbsp;</p>
        <div class="container" style="background-color:  rgba(255, 255, 255, 0.8);"">
     <div class="out_table btn btn-default" >
                <h3>Mailbox transfer</h3>
            </div>       
            <?php echo $this->layout()->content; ?>            
        </div>
        <?php echo $this->headScript()->prependFile($this->baseUrl('/js/bootstrap.min.js')) ?>
    </body>
</html>