<div class="out_table" style="display:<?php echo $this->form_display ?>">
    <div class="out_table_label">Source mailbox parameters:</div>
    <?php echo $this->form ?> 
</div> 

<div class="out_table" style="display:<?php echo $this->form2_display ?> ">
    <div class="out_table_label"  >Target mailbox parameters:</div>
    <?php echo $this->form2 ?> 
</div> 

<div class="out_table" >
    <div class="out_table_label"  style="display: <?php echo $this->table_display ?>" >Transfer parameters <?php echo $this->costam ?></div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Direction</th>
            <th>Host</th>
            <th>User</th>
            <th>Password</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->sources as $server): ?>
            <tr>
                <td><?php echo $this->escape($server[0]); ?></td>
                <td><?php echo $this->escape($server[1]); ?></td>
                <td><?php echo $this->escape($server[2]); ?></td>
                <td><?php echo $this->escape($server[3]); ?></td>
                <td>
                    <a href="<?php echo $this->url(array('controller' => 'multi', 'action' => 'edit', 'id' => $server[4])); ?>" class="btn btn-default" >Edit</a>
                    <a href="<?php echo $this->url(array('controller' => 'multi', 'action' => 'delete', 'id' => $server[4])); ?>" class="btn btn-warning" >Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
            <?php if($this->target){ ?>
                <tr>
                    <td><?php echo $this->target[0]; ?></td>
                    <td><?php echo $this->target[1]; ?></td>
                    <td><?php echo $this->target[2]; ?></td>
                    <td><?php echo $this->target[3]; ?></td>
                    <td>
                        <a href="<?php echo $this->url(array('controller' => 'multi', 'action' => 'edit', 'id' => 'target')); ?>" class="btn btn-default">Edit</a>
                        <a href="<?php echo $this->url(array('controller' => 'multi', 'action' => 'delete', 'id' => 'target')); ?>" class="btn btn-warning">Delete</a>
                    </td>
                </tr>
                <?php } ?>
        <tr>
            <td colspan="5" align="center"><a href="/multi/add" class="btn btn-primary" >Add source server</a>
                &nbsp;&nbsp;<a href="multi/transfer" class="btn btn-primary" >Begin transfer</a>
        </tr>          
    </tbody>
</table>     
</div>