<div class="out_table" style="display: <?php echo $this->table_display ?>" >
    <div class="out_table_label">Transfer history</div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Date</th>
                <th>Source Server</th>
                <th>Source User</th>
                <th>Target Server</th>
                <th>Target User</th>
                <th>Result</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->history as $key => $transfer) : ?>
                <tr>
                    <td><?php echo $transfer['data']; ?></td>
                    <td><?php echo $transfer['source_name']; ?></td>
                    <td><?php echo $transfer['source_user'] ?></td>
                    <td><?php echo $transfer['target_name'] ?></td>
                    <td><?php echo $transfer['target_user'] ?></td>
                    <td><?php echo $transfer['result'] ?></td>
                    <td>
                        <a href="<?php echo $this->url(array('controller' => 'multi', 'action' => 'addtoparam', 'edit' => $transfer['id_transfers'])) ?>" class="btn btn-default">Use it again</a>
                        <a href="<?php echo $this->url(array('controller' => 'multi', 'action' => 'delhistory', 'edit' => $transfer['id_transfers'])) ?>" class="btn btn-warning">Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td colspan="7" align="center"><a href="/multi/history" class="btn btn-primary" <?php echo $this->button_disabled ?>  >Refresh</a>
                </td>
            </tr>
        </tbody>
    </table>
</div>
