<?php //echo $this->flashMessenger()->render(); ?>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body">
                <p>Some text in the modal.</p>
            </div>
            <div class="modal-footer">
                <a href="" type="button" class="btn btn-default" data-dismiss="modal">Close</a>
            </div>
        </div>

    </div>
</div>
<p>to jest do znikniecia</p>

<a href="#"  type="button" class="btn btn-info btn-lg" onclick="myFunction()" data-toggle="modal" >Open Modalto jest testowe hist view</a>
<script>
    function myFunction() {
        
    }
    </script>