<div class="out_table" style="display:<?php echo $this->form_display ?>">
    <div class="out_table_label">Transfer parameters:</div>
    <?php echo $this->form ?> 
</div>

<p id="test">to jest do znikniecia</p>

<a id="button_test" href="#"  type="button" class="btn btn-info btn-lg"  > jest testowe </a>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" >
    <div class="modal-dialog">
        <div class="modal-content" >     
            <div class="modal-body" style="text-align: center">
                <img src="/photos/gears.gif" style="text-align:  center">
            </div>
        </div>
    </div>
</div>