<div class="out_table" style="display:<?php echo $this->form_display ?>">
    <div class="out_table_label">Source mailbox parameters:</div>
    <?php echo $this->form ?> 
</div> 

<div class="out_table" style="display:<?php echo $this->form2_display ?> ">
    <div class="out_table_label"  >Target mailbox parameters:</div>
    <?php echo $this->form2 ?> 
</div> 

<div class="out_table" style="display: <?php echo $this->table_display ?>" >
    <div class="out_table_label">Transfer parameters</div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Direction</th>
                <th>Host</th>
                <th>User</th>
                <th>Password</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->sources as $key => $server) { ?>
                <tr>
                    <td><?php echo $server[0] ?></td>
                    <td><?php echo $server[1] ?></td>
                    <td><?php echo $server[2] ?></td>
                    <td><?php echo $server[3] ?></td>
                    <td>
                        <a href="<?php echo $this->url(array('controller' => 'multi', 'action' => 'param', 'edit' => $key)) ?>" class="btn btn-default">Edit</a>
                        <a href="<?php echo $this->url(array('controller' => 'multi', 'action' => 'delete', 'id' => $key)) ?>" class="btn btn-warning">Delete</a>
                    </td>
                </tr>
            <?php } ?>
                <?php if($this->target){ ?>
                <tr>
                    <td><?php echo $this->target[0]; ?></td>
                    <td><?php echo $this->target[1]; ?></td>
                    <td><?php echo $this->target[2]; ?></td>
                    <td><?php echo $this->target[3]; ?></td>
                    <td>
                        <a href="<?php echo $this->url(array('controller' => 'multi', 'action' => 'edit', 'edit' => 'target')); ?>" class="btn btn-default">Edit</a>
                        <a href="<?php echo $this->url(array('controller' => 'multi', 'action' => 'delete', 'id' => 'target')); ?>" class="btn btn-warning">Delete</a>
                    </td>
                </tr>
                <?php } ?>
            <tr>
                <td colspan="5" align="center">
                    <a href="/multi/transfer" class="btn btn-primary" <?php echo $this->button_disabled ?>  >Begin transfer</a> </td>
            </tr>
            
        </tbody>
    </table>
</div>
